CREATE TABLE O_ROLLCALL(Name VARCHAR(25),RollNo INT,Class VARCHAR(25));

DELIMITER //

CREATE PROCEDURE SOLVE(IN name VARCHAR(25),IN rollno INT ,IN class VARCHAR(25))
BEGIN
INSERT INTO O_ROLLCALL VALUES(name,rollno,class);
END;
//

INSERT INTO O_ROLLCALL VALUES('SAYEED',31144,'TE1');//
INSERT INTO O_ROLLCALL VALUES('SANKET',45638,'TE4');//
INSERT INTO O_ROLLCALL VALUES('VINAYAK',64528,'TE1');//
INSERT INTO O_ROLLCALL VALUES('HARSH',41526,'TE3');//
INSERT INTO O_ROLLCALL VALUES('SHREYASH',41297,'TE4');// 

CREATE TABLE N_ROLLCALL(Name varchar(25),Rollno int,Class varchar(25));//

--
CREATE PROCEDURE CUR()
BEGIN
DECLARE rollno INT;
DECLARE exit_loop BOOLEAN;
DECLARE c1 CURSOR FOR SELECT O_ROLLCALL.RollNo FROM O_ROLLCALL;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET exit_loop=TRUE;
OPEN c1;
emp_loop:LOOP
FETCH c1 INTO rollno;
IF NOT EXISTS (SELECT *FROM N_ROLLCALL WHERE N_ROLLCALL.RollNo=rollno) THEN 
INSERT INTO N_ROLLCALL SELECT *FROM O_ROLLCALL WHERE O_ROLLCALL.RollNo=rollno;
END IF;
IF exit_loop THEN 
CLOSE c1;
LEAVE emp_loop;
END IF;
END LOOP emp_loop;
END;
//

CALL CUR();

SELECT *FROM N_ROLLCALL;//


